name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  pull_request: # Will test luarocks installation on PR, without uploading
jobs:
  luarocks-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          summary: A file explorer tree for neovim written in lua
          detailed_description: |
            Customisable file tree explorer for neovim

            Git, LSP Diagnostics, Auto-Update, Live Filtering, File Icons

            ...and more
          license: "GPL-3.0"
          labels: neovim
          dependencies: |
            nvim-web-devicons
